// Generates the permission schema + links the native mobile sources.
//
// `tauri_plugin::Builder` reads COMMANDS, emits an allow-/deny- pair
// per command under permissions/autogenerated/, and (on mobile target
// builds) tells Tauri where the Swift / Kotlin lives so it gets compiled
// into the app and registered under the plugin name "iap".
const COMMANDS: &[&str] = &["get_products", "purchase", "restore_purchases"];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .ios_path("ios")
        .build();
}
